### ISSUE TITLE
Failure to deploy: cannot import name is_subpath

### ISSUE THREAD

**Issue by freephile** [freephile/qb#3]
### Environment

- Machine or Virtual Machine details: Digital Ocean (demo.qualitybox.us)
- Operating System: CentOS Linux release 7.8.2003 (Core)
- meza version hash: 8b5428d 
```
commit 8b5428d27fbceb41c2476113a2e6c8cfea24604c
Author: Greg Rundlett <greg@equality-tech.com>
Date:   Thu May 7 08:40:07 2020 -0400

    New feature: GoAccess Real-time Web Analytics
```
- Ansible Version
```
ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
### Issue details

```
TASK [database : export dump file on master] *************************************************************************************************************************************************
task path: /opt/meza/src/roles/database/tasks/replication.yml:94
Thursday 07 May 2020  09:41:50 -0400 (0:00:00.095)       0:09:55.843 ********** 
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
ERROR! Unexpected Exception, this is probably a bug: cannot import name is_subpath
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 241, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 248, in run
    action = action_loader.get(task.action, class_only=True)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 557, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 535, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/fetch.py", line 30, in <module>
    from ansible.utils.path import makedirs_safe, is_subpath
ImportError: cannot import name is_subpath
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
su meza-ansible -c "ansible-playbook /opt/meza/src/playbooks/site.yml -i /opt/conf-meza/secret/monolith/hosts --vault-password-file /opt/conf-meza/users/meza-ansible/.vault-pass-monolith.txt --extra-vars '{\"env\": \"monolith\"}' -vvv"
Exiting with return code 64000
```

**Comment by freephile** [comment]
Re-deployed and received no error.
